[book]
title = "Rust ♡ Existing C++"
authors = ["Adrian Taylor"]
description = "autocxx — safe interop between Rust and existing C++"

[rust]
edition = "2018"

[build]
build-dir = "build"
create-missing = false

[preprocessor.autocxx]
command = "../target/debug/autocxx-mdbook-preprocessor"

[output.html]
cname = "autocxx.github.io"
git-repository-url = "https://github.com/google/autocxx"
playground = { copyable = false }
print = { enable = false }
