[package]
name = "autocxx-reduce"
version = "0.13.2"
authors = ["adetaylor <adetaylor@chromium.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx-engine = { version = "=0.13.2", path="../../engine" }
autocxx-parser = { version = "=0.13.2", path="../../parser", features = [ "reproduction_case" ] }
clap = "~2.33.0"
tempfile = "3.1"
indoc = "1.0"
itertools = "0.10"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
syn = "1.0.39"
quote = "1.0"

[dev-dependencies]
assert_cmd = "1.0.3"
tempdir = "0.3.7"
indoc = "1.0"
proc-macro2 = "1.0"