[package]
name = "autocxx-reduce"
version = "0.5.4"
authors = ["adetaylor <adetaylor@chromium.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx-gen = { version = "0.5.4", path="../../gen/cmd" }
autocxx-engine = { version = "0.5.4", path="../../engine" }
clap = "~2.33.0"
tempfile = "3.1"
indoc = "1.0"
itertools = "0.10"
