name: Rustfmt and rustdoc
on:
  push:
    branches: [main]
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - name: check rustfmt
        run: cargo fmt -- --check --color always
      - name: check rustdoc
        # Note that this is `cargo rustdoc` and not `cargo doc`)
        run: |
          for package in $(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | .name'); do
            cargo rustdoc --color always -p "$package" -- -D warnings
          done